//! The one place a semantic error becomes a transport status, and back (spec §6.2, ADR-0010).
//!
//! `config-core` classifies every [`ConfigError`] with [`ConfigError::kind`]; this module is
//! the only code in the tree that turns that classification into a [`tonic::Status`]. Keeping
//! both directions here means the server table and the client's inverse table cannot drift:
//! [`status_from_error`] and [`error_from_status`] are round-trip tested against every
//! variant.
//!
//! # What never goes on the wire
//!
//! Status messages carry the error's operator-facing `Display` only. `ConfigError` is
//! specified never to put a key or value in those fields, so a status message never leaks
//! request content. Structured detail travels as metadata instead, which also keeps the
//! message text non-load-bearing.
//!
//! # Who produced the status
//!
//! A gRPC status code says nothing about *where* it came from, and for a mutation that is the
//! difference between "rejected, resubmit freely" and "may have committed, never replay"
//! (ADR-0015). So every status a server generates carries [`HEADER_OUTCOME`]; a status
//! reaching the client without it was produced by the transport (a reset stream, a refused
//! connection, a proxy) and the client must assume the worst. See
//! [`is_server_rejection`].

use config_core::{ConfigError, LeaderHint, NodeId, StatusClass};
use tonic::metadata::{Ascii, MetadataValue};
use tonic::{Code, Status};

/// Metadata key marking a status as *generated by an rEtcd server* (ADR-0015).
///
/// Its only defined value is [`OUTCOME_REJECTED`]. Absence is the load-bearing case: it means
/// the status was minted by the transport, not by a node that knows the request's fate.
pub const HEADER_OUTCOME: &str = "retcd-outcome";
/// The one value of [`HEADER_OUTCOME`]: the server refused the request and it never entered
/// the log (or the server otherwise knows its outcome).
pub const OUTCOME_REJECTED: &str = "rejected";

/// Metadata key carrying the leader's node id on a `FAILED_PRECONDITION` (ADR-0010).
pub const HEADER_LEADER_NODE_ID: &str = "retcd-leader-node-id";
/// Metadata key carrying the leader's client-plane endpoint on a `FAILED_PRECONDITION`.
pub const HEADER_LEADER_ENDPOINT: &str = "retcd-leader-endpoint";
/// Metadata key carrying `exists` for a [`ConfigError::Conflict`].
///
/// Additive to ADR-0010: `NotLeader` and `Conflict` share `FAILED_PRECONDITION`, so without a
/// structured marker a client could not tell them apart. It carries no key and no value.
pub const HEADER_CONFLICT_EXISTS: &str = "retcd-conflict-exists";
/// Metadata key carrying `current_mod_revision` for a [`ConfigError::Conflict`].
pub const HEADER_CONFLICT_MOD_REVISION: &str = "retcd-conflict-mod-revision";

/// Failures of the transport itself, as opposed to a semantic [`ConfigError`].
#[derive(Debug, thiserror::Error)]
pub enum GrpcError {
    /// A listener could not be bound or queried.
    #[error("io error: {0}")]
    Io(#[from] std::io::Error),
    /// tonic refused the server or channel configuration (usually TLS material).
    #[error("transport error: {0}")]
    Transport(#[from] tonic::transport::Error),
    /// A TLS profile could not be built from the supplied PEM material.
    #[error("tls configuration error: {0}")]
    Tls(String),
    /// An endpoint string was not a usable authority.
    #[error("invalid endpoint {endpoint:?}: {detail}")]
    InvalidEndpoint {
        /// The rejected endpoint.
        endpoint: String,
        /// Why it was rejected.
        detail: String,
    },
    /// The server task ended abnormally: it panicked, or it was cancelled before it drained.
    ///
    /// Reported rather than swallowed, because a panicked serving task and a clean drain are
    /// indistinguishable to a caller that only sees `Ok(())` — and the panicking case is
    /// exactly the one a test must fail on.
    #[error("server task failed: {0}")]
    ServerTask(String),
}

/// The gRPC code a [`StatusClass`] maps to (spec §6.2 normative table).
pub const fn code_for(class: StatusClass) -> Code {
    match class {
        StatusClass::InvalidArgument => Code::InvalidArgument,
        StatusClass::ResourceExhausted => Code::ResourceExhausted,
        StatusClass::Unavailable => Code::Unavailable,
        StatusClass::FailedPrecondition => Code::FailedPrecondition,
        StatusClass::NotFound => Code::NotFound,
        StatusClass::DeadlineExceeded => Code::DeadlineExceeded,
        StatusClass::PermissionDenied => Code::PermissionDenied,
        StatusClass::Unauthenticated => Code::Unauthenticated,
        StatusClass::Internal => Code::Internal,
    }
}

/// Map a semantic error onto the wire.
///
/// `NotLeader` with a validated hint additionally carries `retcd-leader-node-id` and
/// `retcd-leader-endpoint`; `Conflict` carries its two fields as metadata so the client can
/// reconstruct the variant rather than parsing prose. Every status produced here is marked
/// with [`HEADER_OUTCOME`], because a typed [`ConfigError`] is by construction a decision the
/// server reached (ADR-0015).
pub fn status_from_error(err: &ConfigError) -> Status {
    let mut status = mark_rejected(Status::new(code_for(err.kind()), err.to_string()));
    match err {
        ConfigError::NotLeader { hint: Some(hint) } => {
            insert_ascii(
                &mut status,
                HEADER_LEADER_NODE_ID,
                hint.node_id.0.to_string(),
            );
            insert_ascii(&mut status, HEADER_LEADER_ENDPOINT, hint.endpoint.clone());
        }
        ConfigError::Conflict {
            exists,
            current_mod_revision,
        } => {
            insert_ascii(&mut status, HEADER_CONFLICT_EXISTS, exists.to_string());
            insert_ascii(
                &mut status,
                HEADER_CONFLICT_MOD_REVISION,
                current_mod_revision.to_string(),
            );
        }
        _ => {}
    }
    status
}

/// Stamp a status the *server* produced with [`HEADER_OUTCOME`].
///
/// Applied to every refusal a plane emits, including the ones that never reach a
/// [`ConfigError`] (a certificate the client plane will not accept, for instance): those are
/// rejections too, and mis-reporting one as an unknown outcome would send a caller into the
/// ADR-0015 recovery procedure for a request no node ever looked at.
pub fn mark_rejected(mut status: Status) -> Status {
    status.metadata_mut().insert(
        HEADER_OUTCOME,
        MetadataValue::<Ascii>::from_static(OUTCOME_REJECTED),
    );
    status
}

/// Was this status generated by an rEtcd server, rather than by the transport?
///
/// The client's whole safety argument rests on this: an error that a node minted describes a
/// decision, while an error the transport minted describes an interruption, and only the
/// latter can hide a mutation that is still in flight.
pub fn is_server_rejection(status: &Status) -> bool {
    meta_str(status, HEADER_OUTCOME) == Some(OUTCOME_REJECTED)
}

fn insert_ascii(status: &mut Status, key: &'static str, value: String) {
    if let Ok(value) = value.parse::<MetadataValue<Ascii>>() {
        status.metadata_mut().insert(key, value);
    }
}

fn meta_str<'a>(status: &'a Status, key: &str) -> Option<&'a str> {
    status.metadata().get(key).and_then(|v| v.to_str().ok())
}

/// The inverse of [`status_from_error`], used by `config-client`.
///
/// `DEADLINE_EXCEEDED` becomes [`ConfigError::DeadlineExceededUnknownOutcome`], which is the
/// mutation reading (ADR-0015). A read path that produced the deadline itself should override
/// this with [`ConfigError::Unavailable`], because a read has no outcome to be unsure about.
///
/// This table is only meaningful for a status that [`is_server_rejection`] accepts. Applying
/// it to a transport-minted status would read a reset connection as a typed refusal; the
/// client checks the marker first.
pub fn error_from_status(status: &Status) -> ConfigError {
    let detail = status.message().to_string();
    match status.code() {
        Code::InvalidArgument => ConfigError::InvalidArgument { detail },
        Code::ResourceExhausted => ConfigError::ResourceExhausted { detail },
        Code::NotFound => ConfigError::NotFound,
        Code::DeadlineExceeded => ConfigError::DeadlineExceededUnknownOutcome,
        Code::PermissionDenied => ConfigError::PermissionDenied { detail },
        Code::Unauthenticated => ConfigError::Unauthenticated { detail },
        Code::Internal => ConfigError::FatalStorage { detail },
        Code::FailedPrecondition => failed_precondition(status),
        // Everything else — `UNAVAILABLE`, `CANCELLED`, `ABORTED` — is read as a rejection a
        // *server* chose to send, which is only sound because this table is reached only for a
        // status `is_server_rejection` accepted. The same codes without the marker are minted
        // by the transport, and for a mutation ADR-0015 makes them an unknown outcome, never a
        // safe resubmit: `config_client::classify` checks the marker before it gets here, and
        // applying this arm to an unmarked status would be exactly the duplicate-write bug the
        // marker exists to prevent.
        _ => ConfigError::Unavailable { reason: detail },
    }
}

fn failed_precondition(status: &Status) -> ConfigError {
    if let Some(rev) = meta_str(status, HEADER_CONFLICT_MOD_REVISION).and_then(|v| v.parse().ok()) {
        return ConfigError::Conflict {
            exists: meta_str(status, HEADER_CONFLICT_EXISTS) == Some("true"),
            current_mod_revision: rev,
        };
    }
    ConfigError::NotLeader {
        hint: leader_hint(status),
    }
}

/// Read the leader hint a server attached to a `FAILED_PRECONDITION`, if any.
///
/// A *partial* or unparsable hint is dropped, but never silently: half a hint means the peer
/// disagrees with us about the metadata contract, and the symptom — a client that stops
/// following hints — is otherwise invisible in a log.
pub fn leader_hint(status: &Status) -> Option<LeaderHint> {
    let raw_id = meta_str(status, HEADER_LEADER_NODE_ID);
    let raw_endpoint = meta_str(status, HEADER_LEADER_ENDPOINT);
    if raw_id.is_none() && raw_endpoint.is_none() {
        return None;
    }
    let parsed = raw_id
        .and_then(|id| id.parse::<u64>().ok())
        .zip(raw_endpoint.filter(|e| !e.is_empty()));
    match parsed {
        Some((node_id, endpoint)) => Some(LeaderHint {
            node_id: NodeId(node_id),
            endpoint: endpoint.to_string(),
        }),
        None => {
            tracing::warn!(
                leader_node_id = raw_id.unwrap_or("<absent>"),
                leader_endpoint = raw_endpoint.unwrap_or("<absent>"),
                "discarding an unparsable leader hint"
            );
            None
        }
    }
}
